version: '3.4'

services:
  visual-hashing:
    restart: always
    container_name: visualhashing
    image: purwowd/visualhashing:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: "exit 0"

